# Generated by Django 4.1.7 on 2023-03-31 18:49

import datetime
from django.db import migrations, models
import django.db.models.deletion
import school_app.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AnneeScolaire',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('dateDebut', models.DateTimeField(blank=True, null=True)),
                ('dateFin', models.DateTimeField(blank=True, null=True)),
                ('libelle', models.CharField(default=' ', max_length=50)),
            ],
            options={
                'ordering': ['libelle'],
            },
        ),
        migrations.CreateModel(
            name='Cursus',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('libelle', models.CharField(default=' ', max_length=100)),
            ],
            options={
                'ordering': ['libelle'],
            },
        ),
        migrations.CreateModel(
            name='Domaine',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('libelle', models.CharField(default=' ', max_length=100)),
            ],
            options={
                'ordering': ['libelle'],
            },
        ),
        migrations.CreateModel(
            name='EmploiDuTemps',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('dateDebut', models.DateTimeField()),
                ('dateFin', models.DateTimeField()),
                ('code', models.CharField(max_length=50)),
            ],
            options={
                'ordering': ['dateDebut'],
            },
        ),
        migrations.CreateModel(
            name='Enseignant',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(max_length=150)),
                ('prenoms', models.CharField(max_length=150)),
                ('dateNais', models.DateTimeField()),
                ('tel', models.CharField(max_length=50)),
                ('profession', models.CharField(max_length=100)),
                ('email', models.CharField(max_length=100)),
                ('adresse', models.CharField(max_length=100)),
                ('sexe', models.CharField(choices=[('Feminin', 'Feminin'), ('Inconnu', 'Inconnu'), ('Masculin', 'Masculin')], max_length=15)),
                ('dateIndispoDebut', models.DateField(blank=True, null=True)),
                ('dateIndispoFin', models.DateField(blank=True, null=True)),
            ],
            options={
                'ordering': ['nom', 'prenoms'],
            },
        ),
        migrations.CreateModel(
            name='Enseignement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('libelle', models.CharField(blank=True, max_length=150, null=True)),
                ('enseignant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='school_app.enseignant')),
            ],
            options={
                'ordering': ['libelle'],
            },
        ),
        migrations.CreateModel(
            name='Equipement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('libelle', models.CharField(default=' ', max_length=50)),
                ('quantite', models.PositiveIntegerField(default=0)),
            ],
            options={
                'ordering': ['libelle'],
            },
        ),
        migrations.CreateModel(
            name='Etablissement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(max_length=150)),
                ('logo', models.ImageField(upload_to='photos')),
                ('adresse', models.CharField(max_length=150)),
                ('tel', models.CharField(max_length=50)),
                ('email', models.CharField(max_length=50)),
            ],
            options={
                'ordering': ['nom'],
            },
        ),
        migrations.CreateModel(
            name='Filiere',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('libelle', models.CharField(default=' ', max_length=100)),
            ],
            options={
                'ordering': ['libelle'],
            },
        ),
        migrations.CreateModel(
            name='GradeEnseignant',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('libelle', models.CharField(max_length=100)),
            ],
            options={
                'ordering': ['libelle'],
            },
        ),
        migrations.CreateModel(
            name='GradeScolaire',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('libelle', models.CharField(default=' ', max_length=100)),
            ],
            options={
                'ordering': ['libelle'],
            },
        ),
        migrations.CreateModel(
            name='Lieu',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('libelle', models.CharField(default=' ', max_length=99)),
                ('localisation', models.CharField(blank=True, max_length=100, null=True)),
            ],
            options={
                'ordering': ['libelle'],
            },
        ),
        migrations.CreateModel(
            name='Matiere',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('libelle', models.CharField(default=' ', max_length=100)),
            ],
            options={
                'ordering': ['libelle'],
            },
        ),
        migrations.CreateModel(
            name='Niveau',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('libelle', models.CharField(default=' ', max_length=100)),
            ],
            options={
                'ordering': ['libelle'],
            },
        ),
        migrations.CreateModel(
            name='Parcours',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('libelle', models.CharField(max_length=100)),
            ],
            options={
                'ordering': ['libelle'],
            },
        ),
        migrations.CreateModel(
            name='Salle',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('libelle', models.CharField(default=' ', max_length=50)),
                ('capacite', models.PositiveIntegerField(default=0)),
                ('numero', models.CharField(max_length=50)),
            ],
            options={
                'ordering': ['libelle'],
            },
        ),
        migrations.CreateModel(
            name='SeanceCours',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('heureDebut', models.TimeField(default=datetime.datetime(2023, 3, 31, 19, 49, 18, 335270))),
                ('heureFin', models.TimeField(default=datetime.datetime(2023, 3, 31, 19, 49, 18, 335270))),
                ('statut', models.CharField(choices=[('Fait', 'Fait'), ('Non Fait', 'Non Fait')], default='Non Fait', max_length=15)),
                ('typeSeance', models.CharField(choices=[('TD', 'TD'), ('TP', 'TP')], max_length=15)),
                ('emploiDuTemps', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='school_app.emploidutemps')),
                ('enseignement', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='school_app.enseignement')),
                ('lieu', models.ForeignKey(blank=True, default=school_app.models.getDefaultLieu, on_delete=django.db.models.deletion.CASCADE, related_name='models', related_query_name='model', to='school_app.lieu')),
                ('salle', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='school_app.salle')),
            ],
        ),
        migrations.AddField(
            model_name='salle',
            name='enseignement',
            field=models.ManyToManyField(related_name='models', through='school_app.SeanceCours', to='school_app.enseignement'),
        ),
        migrations.CreateModel(
            name='MatiereCursus',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('libelle', models.CharField(default=' ', max_length=200)),
                ('duree', models.PositiveIntegerField(default=1, help_text='En heures')),
                ('cursus', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='school_app.cursus')),
                ('matiere', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='school_app.matiere')),
            ],
            options={
                'ordering': ['libelle'],
            },
        ),
        migrations.AddField(
            model_name='matiere',
            name='cursus',
            field=models.ManyToManyField(related_name='models', through='school_app.MatiereCursus', to='school_app.cursus'),
        ),
        migrations.CreateModel(
            name='MatCursusAnnee',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('libelle', models.CharField(blank=True, default=' ', max_length=50, null=True)),
                ('anneeScolaire', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='school_app.anneescolaire')),
                ('matiereCursus', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='school_app.matierecursus')),
            ],
            options={
                'ordering': ['libelle'],
            },
        ),
        migrations.CreateModel(
            name='Logistique',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('equipement', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='school_app.equipement')),
                ('seanceCours', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='school_app.seancecours')),
            ],
        ),
        migrations.AddField(
            model_name='equipement',
            name='seanceCours',
            field=models.ManyToManyField(related_name='models', through='school_app.Logistique', to='school_app.seancecours'),
        ),
        migrations.AddField(
            model_name='enseignement',
            name='matCursusAnnee',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='school_app.matcursusannee'),
        ),
        migrations.AddField(
            model_name='enseignant',
            name='gradeEnseignant',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='models', related_query_name='model', to='school_app.gradeenseignant'),
        ),
        migrations.AddField(
            model_name='enseignant',
            name='matCursusAnnee',
            field=models.ManyToManyField(related_name='models', through='school_app.Enseignement', to='school_app.matcursusannee'),
        ),
        migrations.AddField(
            model_name='cursus',
            name='domaine',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='models', related_query_name='model', to='school_app.domaine'),
        ),
        migrations.AddField(
            model_name='cursus',
            name='filiere',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='models', related_query_name='model', to='school_app.filiere'),
        ),
        migrations.AddField(
            model_name='cursus',
            name='gradeScolaire',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='models', related_query_name='model', to='school_app.gradescolaire'),
        ),
        migrations.AddField(
            model_name='cursus',
            name='niveau',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='models', related_query_name='model', to='school_app.niveau'),
        ),
        migrations.AddField(
            model_name='cursus',
            name='parcours',
            field=models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, related_name='models', related_query_name='model', to='school_app.parcours'),
        ),
    ]
